services:
  web:
    build: .
    container_name: fyp_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,159.223.85.255
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge